FROM public.ecr.aws/lambda/python:3.12 AS base

RUN dnf update -y && \
    dnf install -y gcc python3-devel git && \
    dnf clean all

ADD pyproject.toml requirements.txt ./
RUN pip install --no-cache-dir . && rm pyproject.toml
RUN pip install --no-cache-dir mangum==0.17.0
COPY mergemate/ ${LAMBDA_TASK_ROOT}/mergemate/

FROM base
CMD ["mergemate.server.health.app"]
